<%@ page contentType="text/html;charset=UTF-8"%>
<%@ include file="/WEB-INF/jsp/manage/common/taglibs.jsp"%>
<div style="padding: 5px;font-family:微软雅黑;">
<table class="tableForm" width="100%">
	<tr>
		<th>主键:</th>
		<td>${memberEnterprise.id}</td>
	</tr>					
	<tr>
		<th width="25%">用户编码:</th>
		<td>${memberEnterprise.userNo}</td>
	</tr>					
	<tr>
		<th>用户名:</th>
		<td>${memberEnterprise.username}</td>
	</tr>					
	<tr>
		<th>企业类型:</th>
		<td>${memberEnterprise.entType.message}</td>
	</tr>					
	<tr>
		<th>企业名称:</th>
		<td>${memberEnterprise.entName}</td>
	</tr>					
	<tr>
		<th>社会统一信用代码:</th>
		<td>${memberEnterprise.licenceNo}</td>
	</tr>					
	<tr>
		<th>营业执照图片地址:</th>
		<td>${memberEnterprise.licencePath}</td>
	</tr>					
	<tr>
		<th>营业执照地址:</th>
		<td>${memberEnterprise.licenceAddress}</td>
	</tr>					
	<tr>
		<th>营业年限:</th>
		<td>${memberEnterprise.businessLife}</td>
	</tr>					
	<tr>
		<th>法人姓名:</th>
		<td>${memberEnterprise.legalName}</td>
	</tr>					
	<tr>
		<th>法人证件类型: 默认身份证:</th>
		<td>${memberEnterprise.legalCertType}</td>
	</tr>					
	<tr>
		<th>法人证件号码:</th>
		<td>${memberEnterprise.legalCertNo}</td>
	</tr>					
	<tr>
		<th>法人证件到期时间:</th>
		<td>${memberEnterprise.legalCertValidTime}</td>
	</tr>					
	<tr>
		<th>法人证件正面图片:</th>
		<td>${memberEnterprise.legalCertFrontPath}</td>
	</tr>					
	<tr>
		<th>法人证件背面图片:</th>
		<td><a class="manage_onlineFile_datagrid_thumbnail" target="_blank"  href="${memberEnterprise.legalCertBackPath}"><img src="${memberEnterprise.legalCertBackPath}" width="100" height="80"/></a>
		</td>
	</tr>					
	<tr>
		<th>经营范围:</th>
		<td>${memberEnterprise.businessScope}</td>
	</tr>					
	<tr>
		<th>实际控股人或企业类型:</th>
		<td>${memberEnterprise.holdingEnum.message}</td>
	</tr>					
	<tr>
		<th>股东或实际控制人真实姓名:</th>
		<td>${memberEnterprise.holdingName}</td>
	</tr>					
	<tr>
		<th>股东或实际控制人证件类型:</th>
		<td>${memberEnterprise.holdingCertType.message}</td>
	</tr>					
	<tr>
		<th>股东或实际控制人证件号:</th>
		<td>${memberEnterprise.holdingCertNo}</td>
	</tr>					
	<tr>
		<th>股东或实际控制人证件到期时间:</th>
		<td>${memberEnterprise.holdingCertValidTime}</td>
	</tr>					
	<tr>
		<th>股东或实际控制人证件正面图片:</th>
		<td>${memberEnterprise.holdingCertFrontPath}</td>
	</tr>					
	<tr>
		<th>股东或实际控制人证件背面图片:</th>
		<td>${memberEnterprise.holdingCertBackPath}</td>
	</tr>					
	<tr>
		<th>开户许可证号码:</th>
		<td>${memberEnterprise.accountLicenseNo}</td>
	</tr>					
	<tr>
		<th>开户许可证图片:</th>
		<td>${memberEnterprise.accountLicensePath}</td>
	</tr>					
	<tr>
		<th>税务登记证号码:</th>
		<td>${memberEnterprise.taxAuthorityNo}</td>
	</tr>					
	<tr>
		<th>税务登记证图片:</th>
		<td>${memberEnterprise.taxAuthorityPath}</td>
	</tr>					
	<tr>
		<th>创建时间:</th>
		<td><fmt:formatDate value="${memberEnterprise.createTime}" pattern="yyyy-MM-dd HH:mm:ss"/></td>
	</tr>					
	<tr>
		<th>更新时间:</th>
		<td><fmt:formatDate value="${memberEnterprise.updateTime}" pattern="yyyy-MM-dd HH:mm:ss"/></td>
	</tr>					
	<tr>
		<th>备注:</th>
		<td>${memberEnterprise.comments}</td>
	</tr>					
</table>
</div>
